//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeffer_FERRETERIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProvProd
    {
        public int IdDetalleProvProd { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdProducto { get; set; }
    
        public virtual proveedores proveedores { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
