//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeffer_FERRETERIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_LOGIN
    {
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> idPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
